### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by agolomoodysaada** [salesforce/kafka-junit#15]
When I created a JUnit 4 test using examples in this library, I ran into this error:

```
java.lang.NoSuchMethodError: org.apache.curator.test.TestingServer.<init>(Lorg/apache/curator/test/InstanceSpec;Z)V

	at com.salesforce.kafka.test.KafkaTestServer.start(KafkaTestServer.java:152)
	at com.salesforce.kafka.test.junit4.SharedKafkaTestResource.before(SharedKafkaTestResource.java:121)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

The block of code that seems to be causing this is

```
    @ClassRule
    public static final SharedKafkaTestResource sharedKafkaTestResource = new SharedKafkaTestResource();
```

Thanks for putting this library together.
Any idea how I can solve this issue?

**Comment by Cs4r** [comment]
Hello,

could you please tell us which versions of kafka-junit, kafka and kafka-clients you're using?

**Comment by stanlemon** [comment]
@agolomoodysaada @Cs4r the libraries tests are run with https://github.com/salesforce/kafka-junit/blob/master/pom.xml#L88 (0.11.0).  These dependencies are marked as provided so you will need to explicitly supply them in your project's pom.

**Comment by agolomoodysaada** [comment]
I found the issue. It was because I had two versions of kafka in different gradle dependencies. By removing the old one (0.8 client), and keeping the new one (1.0.1 client) everything worked great!
Sorry for the confusion

**Comment by Cs4r** [comment]
I knew you had a dependecy issue, that's why I asked 😄 

Glad you fixed it. I don't think this sort of issues should be reported here, though.

**Comment by agolomoodysaada** [comment]
Honestly, it's hard when you don't know if it's a dependency issue or a library issue. Maybe it's because I'm new to Java 😅
