### ISSUE TITLE
SharedKafkaTestResourceScram not compatible with Java 17

### ISSUE THREAD

**Issue by christopher-cudennec** [salesforce/kafka-junit#57]
Hey everyone!

We're currently trying to build our open source library sda-dropwizard-commons with Java 17. That's when we found out that your nice library that we use for integration testing with Kafka also has an issue. (No worries - you're not the only one ;) ). Have a look at the following error message:

```
Error on replacing the zkTestServer
java.lang.RuntimeException: Error on replacing the zkTestServer
	at com.salesforce.kafka.test.SharedKafkaTestResourceScram.setKafkaCluster(SharedKafkaTestResourceScram.java:42)
	at com.salesforce.kafka.test.junit4.SharedKafkaTestResource.before(SharedKafkaTestResource.java:78)
...
Caused by: java.lang.NoSuchFieldException: modifiers
	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
	at com.salesforce.kafka.test.SharedKafkaTestResourceScram.setKafkaCluster(SharedKafkaTestResourceScram.java:35)
	... 55 more
```

I haven't looked much into the details but wanted to raise your attention. Maybe you already have a solution for it? :)

Cheers,

Christopher

**Comment by christopher-cudennec** [comment]
Oops. Self-confused here... Actually that was one of our own classes 😆 . Will ping you if there really is a problem.
